apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: harbor.zeronetanzu.lab/cicd/http:$NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 80
