kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: default-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
