apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: taipower-harbor.zerone.lab/tcbbank/nginxdemos:latest
    ports:
    - containerPort: 80
